name: 公告

on:
  repository_dispatch:
#  watch:
#    types: started
#  schedule:
#    - cron: 0 0 * * *
      
env:
  FILE_NAME: 公告      

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    
    - name: set-env
      run: echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y.%m.%d %H:%M:%S")"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} 🚀 公告 | 有重大更新时发布
        allowUpdates: true
        tag: 公告
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          🚀 食用必看最新[➦4月22日公告及固件说明](https://github.com/bin20088/Bin/blob/master/.github/workflows/公告.md)。
          
    - name: WeChat notification
      run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=${{ env.FILE_NAME }}发布成功
